03/09/2021 00:00:10|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/Users/morpheus/Desktop/bazarr/bazarr/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/Users/morpheus/Desktop/bazarr/bazarr/../libs/requests/models.py", line 943, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/Bazarr/Bazarr2/releases?per_page=100'|
03/09/2021 13:38:48|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/Users/morpheus/Desktop/bazarr/bazarr/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/Users/morpheus/Desktop/bazarr/bazarr/../libs/requests/models.py", line 943, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/Bazarr/Bazarr2/releases?per_page=100'|
03/09/2021 13:39:03|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/Users/morpheus/Desktop/bazarr/bazarr/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/Users/morpheus/Desktop/bazarr/bazarr/../libs/requests/models.py", line 943, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/Bazarr/Bazarr2/releases?per_page=100'|
03/09/2021 13:39:25|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/Users/morpheus/Desktop/bazarr/bazarr/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/Users/morpheus/Desktop/bazarr/bazarr/../libs/requests/models.py", line 943, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/Bazarr/Bazarr2/releases?per_page=100'|
03/09/2021 13:39:48|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/Users/morpheus/Desktop/bazarr/bazarr/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/Users/morpheus/Desktop/bazarr/bazarr/../libs/requests/models.py", line 943, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/Bazarr/Bazarr2/releases?per_page=100'|
03/09/2021 13:39:59|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/Users/morpheus/Desktop/bazarr/bazarr/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/Users/morpheus/Desktop/bazarr/bazarr/../libs/requests/models.py", line 943, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/Bazarr/Bazarr2/releases?per_page=100'|
03/09/2021 13:40:01|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/Users/morpheus/Desktop/bazarr/bazarr/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/Users/morpheus/Desktop/bazarr/bazarr/../libs/requests/models.py", line 943, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/Bazarr/Bazarr2/releases?per_page=100'|
03/09/2021 13:40:01|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
03/09/2021 13:40:47|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/Users/morpheus/Desktop/bazarr/bazarr/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/Users/morpheus/Desktop/bazarr/bazarr/../libs/requests/models.py", line 943, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/Bazarr/Bazarr2/releases?per_page=100'|
03/09/2021 13:40:52|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/Users/morpheus/Desktop/bazarr/bazarr/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/Users/morpheus/Desktop/bazarr/bazarr/../libs/requests/models.py", line 943, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/Bazarr/Bazarr2/releases?per_page=100'|
03/09/2021 13:40:52|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
03/09/2021 13:43:39|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/Users/morpheus/Desktop/bazarr/bazarr/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/Users/morpheus/Desktop/bazarr/bazarr/../libs/requests/models.py", line 943, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/Bazarr/Bazarr2/releases?per_page=100'|
03/09/2021 13:43:41|ERROR   |root                            |Error trying to get releases from Github. Http error.|'Traceback (most recent call last):\n  File "/Users/morpheus/Desktop/bazarr/bazarr/check_update.py", line 23, in check_releases\n    r.raise_for_status()\n  File "/Users/morpheus/Desktop/bazarr/bazarr/../libs/requests/models.py", line 943, in raise_for_status\n    raise HTTPError(http_error_msg, response=self)\nrequests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/Bazarr/Bazarr2/releases?per_page=100'|
03/09/2021 13:43:41|INFO    |root                            |BAZARR is started and waiting for request on http://***.***.***.***:6767|
03/09/2021 13:46:48|ERROR   |root                            |BAZARR cannot parse releases caching file: /Users/morpheus/Desktop/bazarr/data_autonomous/config/releases.txt|'Traceback (most recent call last):\n  File "/Users/morpheus/Desktop/bazarr/bazarr/api.py", line 604, in get\n    with io.open(os.path.join(args.config_dir, \'config\', \'releases.txt\'), \'r\', encoding=\'UTF-8\') as f:\nFileNotFoundError: [Errno 2] No such file or directory: \'/Users/morpheus/Desktop/bazarr/data_autonomous/config/releases.txt\''|
